version: "3.8"

services:
  mongo:
    image: mongo:8.0
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - consul-net

  consul-server-1:
    image: hashicorp/consul:latest
    container_name: consul-server-1
    command: agent -server -bootstrap-expect=3 -client=0.0.0.0 -ui -retry-join=consul-server-2 -retry-join=consul-server-3
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    networks:
      - consul-net

  consul-server-2:
    image: hashicorp/consul:latest
    container_name: consul-server-2
    command: agent -server -client=0.0.0.0 -ui -retry-join=consul-server-1 -retry-join=consul-server-3
    ports:
      - "8501:8500"
    networks:
      - consul-net

  consul-server-3:
    image: hashicorp/consul:latest
    container_name: consul-server-3
    command: agent -server -client=0.0.0.0 -ui -retry-join=consul-server-1 -retry-join=consul-server-2
    ports:
      - "8502:8500"
    networks:
      - consul-net

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    depends_on:
      - consul-server-1
      - consul-server-2
      - consul-server-3
    environment:
      SPRING_CLOUD_CONSUL_HOST: consul-server-1
      SPRING_CLOUD_CONSUL_PORT: 8500
      SPRING_CLOUD_CONSUL_DISCOVERY_HEALTH_CHECK_URL: http://api-gateway:8080/actuator/health
    ports:
      - "8080:8080"
    networks:
      - consul-net

networks:
  consul-net:
    driver: bridge
